apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sb-instanceid-dataiku
  name: sb-instanceid-dataiku
spec:
  replicas: 1
  selector:
    app: sb-instanceid-dataiku
  template:
    metadata:
      labels:
        app: sb-instanceid-dataiku
    spec:
      containers:
      - image: http://dataiku-image-place-holder/dataiku-openshift-orchestratio
        imagePullPolicy: IfNotPresent
        name: dataiku
        ports:
        - containerPort: 10000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: sb-instanceid-dataiku
  name: sb-instanceid-dataiku
spec:
  host: sb-instanceid-dataiku.endpoint-postfix-place-holder
  port:
    targetPort: 10000-tcp
  to:
    kind: Service
    name: sb-instanceid-dataiku
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-instanceid-dataiku
  name: sb-instanceid-dataiku
spec:
  ports:
  - name: 10000-tcp
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: sb-instanceid-dataiku
  sessionAffinity: None
  type: ClusterIP