apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-kafka
  labels:
    service-broker: sb-instanceid-kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    sb-instanceid-kafka: kafka
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-kafka
spec:
  replicas: 3
  selector:
    sb-instanceid-kafka: kafka
  template:
    metadata:
      labels:
        sb-instanceid-kafka: kafka
        service-broker: sb-instanceid-kafka
    spec:
      containers:
      - name: kafka
        image: http://kafka-image-place-holder/kafka-openshift-orchestration
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: DEFAULT_REPLICATION_FACTOR
            value: "3"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BROKER_ID_PROTOTYPE
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: sb-instanceid-zk.local-service-postfix-place-holder:2181
            # assume zookeeper port is 2181 here
          - name: KAFKA_CREATE_TOPICS
            value: topic-test1:6:3

