apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    servicebroker: sb-instanceid-kettle
  name: sb-instanceid-kettle
spec:
  replicas: 1
  selector:
    servicebroker: sb-instanceid-kettle
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-kettle
    spec:
      containers:
      - image: http://kettle-image-place-holder/kettle-openshift-orchestration
        name: sb-instanceid-kettle
        resources:
          limits:
            cpu: 0.1
        env:
          - name: a
            value: b
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Route
metadata:
  name: sb-instanceid-kettle
  labels:
    servicebroker: sb-instanceid-kettle
spec:
  host: sb-instanceid-kettle.endpoint-postfix-place-holder
  port:
    targetPort: web
  to:
    kind: Service
    name: sb-instanceid-kettle
---
apiVersion: v1
kind: Service
metadata:
  labels:
    servicebroker: sb-instanceid-kettle
  name: sb-instanceid-kettle
spec:
  ports:
  - port: 8000
    name: web
  selector:
    servicebroker: sb-instanceid-kettle
