apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-redis-master
spec:
  replicas: 1
  selector:
    sb-instanceid-redis-master: master
  template:
    metadata:
      labels:
        sb-instanceid-redis-master: master
        servicebroker: sb-instanceid-redis
      name: sb-instanceid-redisbt
    spec:
      containers:
        - name: sb-nginx
          image: http://redis-image-place-holder/redis-openshift-orchestration
          imagePullPolicy: IfNotPresent
          env:
            - name: hello
              value: nginx
          ports:
            - containerPort: 80

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
