apiVersion: v1
kind: Service
metadata:
  labels:
    servicebroker: sb-instanceid-redis
  name: sb-instanceid-redis
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    sb-instanceid-sentinel: sentinel
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-redis
spec:
  replicas: 2
  selector:
    sb-instanceid-redis: redis
  template:
    metadata:
      labels:
        sb-instanceid-redis: redis
        servicebroker: sb-instanceid-redis
    spec:
      containers:
      - name: redis
        image: http://redis-image-place-holder/redis-openshift-orchestration
        env:
          - name: SENTINEL_HOST
            value: sb-instanceid-redis
          - name: SENTINEL_PORT
            value: "26379"
          - name: REDIS_PASSWORD
            value: pass*****
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-redis-sentinel
spec:
  replicas: 2
  selector:
    sb-instanceid-sentinel: sentinel
  template:
    metadata:
      labels:
        sb-instanceid-sentinel: sentinel
        servicebroker: sb-instanceid-redis
    spec:
      containers:
      - name: sentinel
        image: http://redis-image-place-holder/redis-openshift-orchestration
        env:
          - name: SENTINEL
            value: "true"
          - name: SENTINEL_HOST
            value: sb-instanceid-redis
          - name: SENTINEL_PORT
            value: "26379"
          - name: REDIS_PASSWORD
            value: pass*****
        ports:
          - containerPort: 26379