kind: ReplicationController
apiVersion: v1
metadata:
  name: sb-instanceid-sparkzp
spec:
  replicas: 1
  selector:
    servicebroker: sb-instanceid-spark-zepplin
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-spark-zepplin
    spec:
      containers:
        - name: sb-instanceid-sparkzp
          env: 
            - name: SPARK_MASTER
              value: sb-instanceid-sparkms.local-service-postfix-place-holder
            - name: SPARK_SECRET
              value: test-1234
          image: index.alauda.cn/asiainfoldp/zepplin
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m

---

kind: Service
apiVersion: v1
metadata:
  name: sb-instanceid-sparkzp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    servicebroker: sb-instanceid-spark-zepplin

---

apiVersion: v1
kind: Route
metadata:
  name: sb-instanceid-sparkzp
spec:
  host: sb-instanceid-spark-zeppelin-servicebroker.endpoint-postfix-place-holder
  to:
    kind: Service
    name: sb-instanceid-sparkzp


