kind: ReplicationController
apiVersion: v1
metadata:
  name: sb-instanceid-sparkwk
spec:
  replicas: num-workers-place-holder
  selector:
    servicebroker: sb-instanceid-spark-worker
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-spark-worker
    spec:
      containers:
        - name: sb-instanceid-sparkwk
          env: 
            - name: SPARK_MASTER
              value: sb-instanceid-sparkms.local-service-postfix-place-holder
            - name: SPARK_SECRET
              value: test-1234
          image: index.alauda.cn/asiainfoldp/spark
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

