kind: ReplicationController
apiVersion: v1
metadata:
  name: sb-instanceid-sparkwk
spec:
  replicas: num-workers-place-holder
  selector:
    servicebroker: sb-instanceid-spark-worker
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-spark-worker
    spec:
      containers:
        - name: sb-instanceid-sparkwk
          env: 
            - name: SPARK_MASTER
              value: sb-instanceid-sparkms.local-service-postfix-place-holder
            - name: SPARK_SECRET
              value: pass*****
          image: http://spark-image-place-holder/spark-openshift-orchestration
          imagePullPolicy: IfNotPresent
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

