kind: ReplicationController
apiVersion: v1
metadata:
  name: sb-instanceid-zppln
spec:
  replicas: 1
  selector:
    servicebroker: sb-instanceid-zppln
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-zppln
    spec:
      containers:
        - name: sb-instanceid-zppln
          env: 
            - name: SPARK_MASTER
              value: sb-instanceid-sm
            - name: SPARK_SECRET
              value: test1234
          image: index.alauda.cn/asiainfoldp/zepplin
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m

---

kind: Service
apiVersion: v1
metadata:
  name: sb-instanceid-zppln
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    servicebroker: sb-instanceid-zppln

---

apiVersion: v1
kind: Route
metadata:
  name: sb-instanceid-zppln
spec:
  host: sb-instanceid-zppln-servicebroker.app.asiainfodata.com
  to:
    kind: Service
    name: sb-instanceid-zppln


