

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-ss
spec:
  replicas: 2
  selector:
    sb-instanceid-storm: supervisor
  template:
    metadata:
      labels:
        sb-instanceid-storm: supervisor
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: zookeeper
        image: http://storm-image-place-holder/storm-openshift-orchestration
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "supervisor"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "external-zookeeper-server1*****"
        - name: ZK_SERVER_2_SERVICE_HOST
          value: "external-zookeeper-server2*****"
        - name: ZK_SERVER_3_SERVICE_HOST
          value: "external-zookeeper-server3*****"
        - name: APACHE_STORM_NIMBUS_SERVICE_HOST
          value: sb-instanceid-sn
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-su
spec:
  selector:
    sb-instanceid-storm: ui
  ports:
  - protocol: TCP
    port: 8080
  externalIPs:
  - externalips*****

---

apiVersion: v1
kind: Route
metadata:
  name: sb-instanceid-su
spec:
  host: sb-instanceid-stormui.endpoint-postfix-place-holder
  port:
    targetPort: storm-ui-port
  to:
    kind: Service
    name: sb-instanceid-su

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-su
spec:
  replicas: 1
  selector:
    sb-instanceid-storm: ui
  template:
    metadata:
      labels:
        sb-instanceid-storm: ui
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: ui
        image: http://storm-image-place-holder/storm-openshift-orchestration
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 8080
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "ui"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "external-zookeeper-server1*****"
        - name: ZK_SERVER_2_SERVICE_HOST
          value: "external-zookeeper-server2*****"
        - name: ZK_SERVER_3_SERVICE_HOST
          value: "external-zookeeper-server3*****"
        - name: APACHE_STORM_NIMBUS_SERVICE_HOST
          value: sb-instanceid-sn
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-sd
spec:
  selector:
    sb-instanceid-storm: drpc
  ports:
  - protocol: TCP
    port: 3772
  externalIPs:
  - externalips*****

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-sd
spec:
  replicas: 1
  selector:
    sb-instanceid-storm: drpc
  template:
    metadata:
      labels:
        sb-instanceid-storm: drpc
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: zookeeper
        image: http://storm-image-place-holder/storm-openshift-orchestration
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 3772
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "drpc"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "external-zookeeper-server1*****"
        - name: ZK_SERVER_2_SERVICE_HOST
          value: "external-zookeeper-server2*****"
        - name: ZK_SERVER_3_SERVICE_HOST
          value: "external-zookeeper-server3*****"
        - name: APACHE_STORM_NIMBUS_SERVICE_HOST
          value: sb-instanceid-sn
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

