apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-sn
spec:
  selector:
    sb-instanceid-storm: nimbus
  ports:
  - protocol: TCP
    port: 6627
    name: storm-nimbus-port
  externalIPs:
  - externalips*****

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-sn
spec:
  replicas: 1
  selector:
    sb-instanceid-storm: nimbus
  template:
    metadata:
      labels:
        sb-instanceid-storm: nimbus
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: nimbus
        image: http://storm-image-place-holder/storm-openshift-orchestration
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 6627
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "nimbus"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "external-zookeeper-server1*****"
        - name: ZK_SERVER_2_SERVICE_HOST
          value: "external-zookeeper-server2*****"
        - name: ZK_SERVER_3_SERVICE_HOST
          value: "external-zookeeper-server3*****"
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}
