apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sb-instanceid-zeppelin
  name: sb-instanceid-zeppelin
spec:
  replicas: 1
  selector:
    app: sb-instanceid-zeppelin
  template:
    metadata:
      labels:
        app: sb-instanceid-zeppelin
    spec:
      containers:
      - image: http://zeppelin-image-place-holder/zeppelin-openshift-orchestration
        imagePullPolicy: IfNotPresent
        name: dataiku
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: sb-instanceid-zeppelin
  name: sb-instanceid-zeppelin
spec:
  host: sb-instanceid-zeppelin.endpoint-postfix-place-holder
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: sb-instanceid-zeppelin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-instanceid-zeppelin
  name: sb-instanceid-zeppelin
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sb-instanceid-zeppelin
  sessionAffinity: None
  type: ClusterIP