apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2018-04-28T04:27:05Z
  generation: 149
  labels:
    app: servicebroker-openshift
  name: servicebroker-openshift
  namespace: service-brokers
  resourceVersion: "8748129"
  selfLink: /oapi/v1/namespaces/service-brokers/deploymentconfigs/servicebroker-openshift
  uid: 684c2eec-4a9c-11e8-ba43-fa163ef134de
spec:
  replicas: 1
  selector:
    app: servicebroker-openshift
    deploymentconfig: servicebroker-openshift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: servicebroker-openshift
        deploymentconfig: servicebroker-openshift
    spec:
      containers:
      - env:
        - name: BROKERPORT
          value: "8888"
        - name: CASSANDRAIMAGE
          value: 172.25.163.133:5000/service-brokers/cassandra-openshift-orchestration-3
        - name: DATAFOUNDRYPROXYADDR
          value: 172.25.145.7:9095
        - name: DNSMASQ_SERVER
          value: 192.168.12.8
        - name: ELASTICSEARCHVOLUMEIMAGE
          value: 172.25.163.133:5000/service-brokers/elasticsearch
        - name: ENDPOINTSUFFIX
          value: lo.dataos.io
        - name: ETCDBOOTIMAGE
          value: 172.25.163.133:5000/service-brokers/etcd-imported:v2.3.0
        - name: ETCDENDPOINT
          value: http://10.1.234.40:2379
        - name: ETCDIMAGE
          value: 172.25.163.133:5000/service-brokers/etcd-openshift-orchestration-2
        - name: ETCDPASSWORD
          value: rootpasswd
        - name: ETCDUSER
          value: root
        - name: ETCDVOLUMEIMAGE
          value: 172.25.163.133:5000/service-brokers/service-brokers-etcd-volumes
        - name: KAFKAIMAGE
          value: 172.25.163.133:5000/service-brokers/kafka-openshift-orchestration
        - name: KETTLEIMAGE
          value: 172.25.163.133:5000/service-brokers/kettle-service-2
        - name: MONGOVOLUMEIMAGE
          value: 172.25.163.133:5000/service-brokers/mongo-volumes
        - name: NIFIIMAGE
          value: 172.25.163.133:5000/service-brokers/nifi-imported
        - name: NODE_ADDRESSES
          value: 10.1.234.35,10.1.234.36,10.1.234.37,10.1.234.38
        - name: OPENSHIFTADDR
          value: 10.1.234.34:443
        - name: OPENSHIFTPASS
          value: "1234"
        - name: OPENSHIFTUSER
          value: hack
        - name: PYSPIDERIMAGE
          value: 172.25.163.133:5000/service-brokers/pyspider
        - name: RABBITMQIMAGE
          value: 172.25.163.133:5000/service-brokers/service-brokers-rabbitmq-volumes
        - name: REDISIMAGE
          value: registry.new.dataos.io/service-brokers/redis-single-master:3.2
        - name: REDISPHPADMINIMAGE
          value: 172.25.163.133:5000/service-brokers/php-redis-admin-imported
        - name: SBNAMESPACE
          value: service-brokers
        - name: SIMPLEFILEUPLOADERIMAGE
          value: 172.25.163.133:5000/service-brokers/simple-file-uploader
        - name: SPARKIMAGE
          value: 172.25.163.133:5000/service-brokers/spark-imported
        - name: STORMIMAGE
          value: 172.25.163.133:5000/service-brokers/storm-openshift-orchestration:v10_dep_dns
        - name: TENSORFLOWIMAGE
          value: 172.25.163.133:5000/service-brokers/tensorflow-imported:0.8.0123123
        - name: ZEPPLINIMAGE
          value: registry.new.dataos.io/zeppelin/zeppelin:0.7.3
        - name: ZOOKEEPEREXHIBITORIMAGE
          value: registry.dataos.io/serviceborker/zookeeper-exhibitor-imported-2:latest
        - name: ZOOKEEPERIMAGE
          value: registry.dataos.io/servicebroker/zookeeper-openshift-orchestration:latest
        - name: REDISCLUSTERIMAGE
          value: registry.new.dataos.io/service-brokers/redis-cluster-plus-trib:4.0.2-v1
        - name: REDISCLUSTERTRIBIMAGE
          value: registry.new.dataos.io/service-brokers/redis-cluster-plus-trib:4.0.2-v1
        - name: KAFKAVOLUMEIMAGE
          value: 172.25.163.133:5000/service-brokers/service-brokers-kafka-volumes
        - name: NEO4JVOLUMEIMAGE
          value: 172.25.163.133:5000/service-brokers/neo4j
        - name: REDIS32IMAGE
          value: registry.new.dataos.io/service-brokers/redis-single-master:3.2
        - name: NODE_DOMAINS
          value: 10.1.234.35.xip.io,10.1.234.36.xip.io,10.1.234.37.xip.io,10.1.234.38.xip.io
        - name: STORMEXTERNALIMAGE
          value: registry.new.dataos.io/service-brokers/storm:multiple-workers-v1
        - name: EXTERNALZOOKEEPERSERVERS
          value: 172.25.187.24,172.25.75.20,172.25.213.2
        - name: OCSP_OCM
          value: temp11
        - name: OCSP_OCM_PORT
          value: temp11
        - name: OCSP_HDP_VERSION
          value: temp11
        - name: OCSPIMAGE
          value: temp
        - name: DATAIKUIMAGE
          value: registry.new.dataos.io/dataiku/dataiku:latest
        - name: ANACONDAIMAGE
          value: registry.new.dataos.io/lixw/base-notebook:v1
        - name: MARIADBIMAGE
          value: registry.new.dataos.io/service-brokers/mariadb:10.2-custom-v21
        - name: PROMETHEUSMYSQLEXPORTERIMAGE
          value: registry.new.dataos.io/service-brokers/prometheus-mysqld_exporter:v0.10.0
        - name: PHPMYADMINIMAGE
          value: registry.new.dataos.io/service-brokers/phpmyadmin:4.6
        - name: STORAGECLASSNAME
          value: gluster-heketi
        - name: ESCLUSTERIMAGE
          value: registry.new.dataos.io/service-brokers/elasticsearch:6.2.2
        - name: REDISSTATIMAGE
          value: registry.new.dataos.io/service-brokers/redis-stat:jre-alpine
        image: docker-registry.default.svc:5000/service-brokers/servicebroker-openshift@sha256:2e62828ab456a12fc5a59dc5970c33337109458df6803501d961883d4c6e20c9
        imagePullPolicy: Always
        name: servicebroker-openshift
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - servicebroker-openshift
      from:
        kind: ImageStreamTag
        name: servicebroker-openshift:latest
        namespace: service-brokers
      lastTriggeredImage: docker-registry.default.svc:5000/service-brokers/servicebroker-openshift@sha256:2e62828ab456a12fc5a59dc5970c33337109458df6803501d961883d4c6e20c9
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-30T07:08:04Z
    lastUpdateTime: 2018-05-30T07:08:04Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-06-01T09:37:00Z
    lastUpdateTime: 2018-06-01T09:37:03Z
    message: replication controller "servicebroker-openshift-83" successfully rolled
      out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: servicebroker-openshift:latest
          namespace: service-brokers
      type: ImageChange
    message: image change
  latestVersion: 83
  observedGeneration: 149
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1

